config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

resources :posts, except: [:destroy] do
  resources :comments, only: [:create]
end

resources :categories, only: [:create, :new, :show]


 #get 'posts', to: 'posts#index'

 #get '/posts/new', to: 'posts#new'
 #post '/posts', to: 'posts#create'
 #get '/posts/:id', to: 'posts#show'
 #get '/posts/:id/edit', to: 'posts#edit'
 #put '/posts/:id', to: 'posts#update'
 #patch '/posts/:id', to: 'posts#update'
 #delete '/posts/:id', to: 'posts#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, length: { maximum: 30}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  validates :body, presence: true, length: { minimum: 5, maximum: 30}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 5, maximum: 30}
  validates :url, presence: true, length: { maximum: 50}
  validates :description, presence: true

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery #with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end


  def create
    @category = Category.new(params[:category].permit!)
    if @category.save
      redirect_to root_path, notice: "Category has been created."
    else
      render :new
    end

  end

  private


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment].permit!)
    if @comment.save
     redirect_to post_path(params[:post_id]), notice: "Your comment was added."

   else

     render 'posts/show'

   end

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update]

  def index
    @post = Post.all
  end

  def show
    #binding.pry
    @comment = Comment.new


  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit!)
    if @post.save
      redirect_to root_path, notice: "You have successfully created a new post"
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @post.update(params[:post].permit!)
      redirect_to root_path, notice: "You've successfully updated the post"
    else
      render :edit
    end

  end

private

  def set_post
        @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<p class="lead">New Category</p>

<%= render "shared/errors", obj: @category %>

<%= form_for @category do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit "Create Category", class: "btn btn-success"%>

<% end %>

app/views/categories/show.html.erb
<p class="lead">All Posts >> <%= @category.name %></p>
<% @category.posts.each do |post| %>
<div class="well">
<h4><%= link_to post.title %></h4>
<br/>
 <p><%= post.description %></p>
 <br/>
<%= link_to "#{post.comments.count} comment", post_path(post.id) %>
<br/>
</div>

<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">

  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <li>
    <%= link_to 'All Posts', posts_path %>
  </li>

  <li>
      <div class="btn-group">
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
              Categories
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <!-- dropdown menu links -->
                <% Category.all.each do |cat| %>
                <li>
                <%= link_to cat.name, category_path(cat.id) %>
              </li>
              <% end %>
                <li class="divider"></li>
                <li>
                  <i class="icon-plus"></i>
                  <i><%= link_to "New Category", new_category_path %></i>
                </li>
            </ul>
      </div>
  </li>
<li class="divider-vertical"></li>


      <a href="/posts/new" class="btn btn-small btn-success">New Post</a>


      <div class="btn-group">
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
              Login
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <!-- dropdown menu links -->
                <li>
                  <a href="user/edit"><i class="icon-pencil"></i> edit profile</a>
                </li>
                <li>
                  <a href="user/"><i class="icon-user"></i> view profile</a>
                </li>
                <li>
                  <a href="user/edit"><i class="icon-circle-arrow-left"></i> log out</a>
                </li>
                  </ul>
      </div>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_post_edit_form.html.erb
<%= form_for obj do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
<br/>
  <%= f.label :description %>
  <%= f.text_area :description %>
<br/>
  <%= f.submit obj.new_record? ? 'Create Post' : 'Update Post', class: 'btn' %>
<% end %>

app/views/posts/edit.html.erb
<p class=lead>Edit Post</p>

<%= render 'shared/errors', obj: @post %>
<%= render 'post_edit_form', obj: @post %>

app/views/posts/index.html.erb
<p class="lead"> All Posts </p>
<hr>

<% @post.each do |p|  %>
<div class="well">


 <h4><%= link_to p.title, p.url  %> </h4>
 <br/>

 <p><%= p.description %></p>
 <br/>

 <%= link_to "#{p.comments.count} comment", post_path(p.id) %>

<br/>

</div>
<% end %>

app/views/posts/new.html.erb
<!--<h4>Model backed forms</h4> -->
<h4> New Post</h4>

<%= render 'shared/errors', obj: @post %>

<%= render 'post_edit_form', obj: @post %>

app/views/posts/show.html.erb
<p class="lead"><%=@post.title %></p>

<%= render 'shared/errors', obj: @comment %>

<%= form_for @comment, url: post_comments_path(@post) do |f| %>
<%= f.label :body %>
<%= f.text_area :body %>
<br/>
<%= f.submit "Create Comment", class: 'btn' %>

<% end %>

<strong>Comments: </strong>

<ul>
<% @post.comments.each do |comment|  %>
<li><%= comment.body  %></li>

<% end %>
</ul>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class = "alert alert-error">
    <p><strong>Please fix the following errors:</strong></p>

    <% obj.errors.full_messages.each do |msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
  </div>
<% end %>